---
- name: Ensure log groups {{ item.log_group_name }} exist
# TODO: When retention for log group is different for each log stream, the values get overriden by the last entry.
  cloudwatchlogs_log_group:
    log_group_name: "{{ item.log_group_name }}"
    retention: "{{ item.log_retention|int }}"
    tags: "{{ item.log_group_tags }}"
    region: "{{ aws_cwa_region }}"
  delegate_to: localhost
  become: no

- name: Ensure log group {{ item.log_group_name }} matrics exist
  cloudwatchlogs_log_group_metric_filter:
    log_group_name: "{{ item.log_group_name }}"
    state: present
    filter_name: "{{ filter.name }}"
    filter_pattern: "{{ filter.pattern }}"
    metric_transformation:
      metric_name: "{{ filter.metric_transformation.metric_name }}"
      metric_namespace: "{{ aws_cwa_namespace }}"
      metric_value: "{{ filter.metric_transformation.metric_value }}"
    region: "{{ aws_cwa_region }}"
  with_items: "{{ item.filters | default([]) }}"
  loop_control:
    loop_var: filter
    label: "{{ item.log_group_name }}"
  delegate_to: localhost
  become: no
