---
- name: Ensure /root/.aws/ is there
  file:
    path: '/root/.aws/'
    state: 'directory'
    mode: '0700'
    owner: 'root'
    group: 'root'

- name: Add AWS CWA profile to /root/.aws/config
  blockinfile:
    path: '/root/.aws/config'
    create: 'yes'
    owner: 'root'
    group: 'root'
    mode: 0600
    marker: "# {mark} ansible aws-cwa cfg"
    block: |
      [profile AmazonCloudWatchAgent]
      output = json
      region = {{aws_cwa_region|default('us-east-1')}}
  notify: restart amazon-cloudwatch-agent

- name: Add AWS CWA profile to /root/.aws/credentials
  blockinfile:
    path: '/root/.aws/credentials'
    create: 'yes'
    owner: 'root'
    group: 'root'
    mode: 0600
    marker: "# {mark} ansible aws-cwa cfg"
    block: |
      [AmazonCloudWatchAgent]
      aws_access_key_id={{aws_cwa_key_access}}
      aws_secret_access_key={{aws_cwa_key_secret}}
  notify: restart amazon-cloudwatch-agent
  no_log: True

- name: Install pre-requisits
  package:
    name: unzip
    state: present

- name: Already installed?
  package:
    name: amazon-cloudwatch-agent
    state: present
  ignore_errors: yes
  register: already_inst

- block:
  - block:
    - name: purge existing pkg if installed
      package:
        name: amazon-cloudwatch-agent
        state: absent
        purge: yes
    - name: purge dir tree if exists
      file:
        path: '/opt/aws/amazon-cloudwatch-agent'
        state: absent
    when: (already_inst is success)
  - name: make temp dir for installation files
    file:
      path: "/tmp/aws-cwa-inst"
      state: "directory"
  - name: download & unpack the latest cloudwatch agent .zip
    unarchive:
      remote_src: "yes"
      src: "https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip"
      dest: "/tmp/aws-cwa-inst/"
  - name: run the installer
    shell: cd /tmp/aws-cwa-inst && echo 'N' | ./install.sh
    notify: restart amazon-cloudwatch-agent
  - name: remove temp dir
    file:
      path: "/tmp/aws-cwa-inst/"
      state: "absent"
  when: (already_inst is failed) or (aws_install_latest is defined) 
  #ignore_errors: "{{ ansible_check_mode }}"

- name: place cfgs, ie. amazon-cloudwatch-agent.json
  template:
    src: "{{ aws_cwa_cfgs }}"
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json"
    mode: 0644
  notify: restart amazon-cloudwatch-agent

- name: Install Python modules
  become: yes
  pip:
    name:
      - boto3
  delegate_to: localhost

- name: Ensure log groups exist
  cloudwatchlogs_log_group:
    log_group_name: "{{ item.log_group_name }}"
    retention: "{{item.log_retention|int}}"
    tags: "{{item.log_group_tags}}"
    aws_access_key: "{{ aws_access_key | default(lookup('env','AWS_ACCESS_KEY_ID')) }}"
    aws_secret_key: "{{ aws_secret_key | default(lookup('env','AWS_SECRET_ACCESS_KEY')) }}"
    region: "{{ aws_region }}"
  with_items: "{{ aws_cwa_logfiles | default([]) }}"
  loop_control:
    label: "{{ item.log_group_name }}"
  delegate_to: localhost

- name: Enable service on boot
  service:
    name: "amazon-cloudwatch-agent"
    enabled: "yes"

- name: Add log rotation for amazon-cloudwatch-agent.log
  copy:
    dest: '/etc/logrotate.d/aws-cwa'
    owner: 'root'
    group: 'root'
    content: |
        /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log {
            size 50M
            rotate 5
            compress
            missingok
            copytruncate
        }
