---
- name: Ensure /root/.aws/ is there
  file:
    path: '/root/.aws/'
    state: 'directory'
    mode: '0700'
    owner: 'root'
    group: 'root'

- name: Add AWS CWA profile to /root/.aws/config
  blockinfile:
    path: '/root/.aws/config'
    create: 'yes'
    owner: 'root'
    group: 'root'
    mode: 0600
    marker: "# {mark} ansible aws-cwa cfg"
    block: |
      [profile AmazonCloudWatchAgent]
      output = json
      region = {{aws_cwa_region|default('us-east-1')}}
  notify: restart amazon-cloudwatch-agent

- name: Add AWS CWA profile to /root/.aws/credentials
  blockinfile:
    path: '/root/.aws/credentials'
    create: 'yes'
    owner: 'root'
    group: 'root'
    mode: 0600
    marker: "# {mark} ansible aws-cwa cfg"
    block: |
      [AmazonCloudWatchAgent]
      aws_access_key_id={{aws_cwa_key_access}}
      aws_secret_access_key={{aws_cwa_key_secret}}
  notify: restart amazon-cloudwatch-agent
  no_log: True

- name: Cloudwatch Update - make temp dir for installation files
  file:
    path: "/tmp/aws-cwa-inst"
    state: "directory"
  tag: cloudwatch-update
- name: Cloudwatch Update - download & unpack the latest cloudwatch agent .zip
  unarchive:
    remote_src: "yes"
    src: "https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip"
    dest: "/tmp/aws-cwa-inst/"
  tag: cloudwatch-update
- name: Cloudwatch Update - run the installer
  shell: cd /tmp/aws-cwa-inst && ./install.sh
  notify: restart amazon-cloudwatch-agent
  tag: cloudwatch-update
- name: Cloudwatch Update - remove temp dir
  file:
    path: "/tmp/aws-cwa-inst/"
    state: "absent"
  tag: cloudwatch-update

- name: Already installed?
  stat:
    path: /opt/aws/amazon-cloudwatch-agent
  register: already_inst

- block:
  - name: make temp dir for installation files
    file:
      path: "/tmp/aws-cwa-inst"
      state: "directory"
  - name: download & unpack the latest cloudwatch agent .zip
    unarchive:
      remote_src: "yes"
      src: "https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip"
      dest: "/tmp/aws-cwa-inst/"
  - name: run the installer
    shell: cd /tmp/aws-cwa-inst && ./install.sh
    notify: restart amazon-cloudwatch-agent
  - name: remove temp dir
    file:
      path: "/tmp/aws-cwa-inst/"
      state: "absent"
  when: already_inst.stat.exists != True
  ignore_errors: "{{ ansible_check_mode }}"

- name: place cfgs, ie. amazon-cloudwatch-agent.(json|toml)
  template:
    src: "{{ item }}"
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/{{ item | basename | regex_replace('\\.j2$', '') }}"
    mode: 0644
  with_fileglob:
  - "{{aws_cwa_cfgs}}/*.j2"
  notify: restart amazon-cloudwatch-agent

- name: check if awscli bundle is already installed
  stat:
    path: '/usr/local/bin/aws'
  register: awscli_installed

- name: Install AWSCLI bundle
  block:
  - name: mkdir temp for awscli install
    file:
      path: '/tmp/awscli-inst'
      state: 'directory'
      owner: 'root'
      group: 'root'
      mode: '0700'

  - name: download awscli bundle
    unarchive:
      remote_src: 'yes'
      src: 'https://s3.amazonaws.com/aws-cli/awscli-bundle.zip'
      dest: '/tmp/awscli-inst/'

  - name: run awscli install script
    shell: ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    args:
      chdir: '/tmp/awscli-inst/'

  - name: rm temp for awscli install
    file:
      path: '/tmp/awscli-inst'
      state: 'absent'
  when: awscli_installed.stat.exists != True
  ignore_errors: "{{ ansible_check_mode }}"

- name: ensure log groups exist
  shell: |
    aws --profile AmazonCloudWatchAgent logs create-log-group --log-group-name {{item.log_group_name}}{% if item.log_group_tags is defined and item.log_group_tags|length > 0 %} --tags {% for lgti in item.log_group_tags %}{% for tK in lgti %}{{tK}}={{ lgti[ tK ] }}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}{% endif %}{{ "" }}
  args:
    executable: '/bin/bash'
  register: create_log_groups
  with_items: "{{ aws_cwa_logfiles | default([]) }}"
  run_once: true
  failed_when: create_log_groups.rc != 0 and create_log_groups.rc != 255

- name: ensure retention policies are up to date
  shell: |
    {% if item.log_retention|default('') != '' %}
    aws --profile AmazonCloudWatchAgent logs put-retention-policy --log-group-name {{item.log_group_name}} --retention-in-days {{item.log_retention}}
    {% else %}
    aws --profile AmazonCloudWatchAgent logs delete-retention-policy --log-group-name {{item.log_group_name}}
    {% endif %}
  args:
    executable: '/bin/bash'
  register: create_log_groups
  with_items: "{{ aws_cwa_logfiles | default([]) }}"
  run_once: true
  failed_when: create_log_groups.rc != 0 and create_log_groups.rc != 255


- name: update start-amazon-cloudwatch-agent with our version (which avoids overwriting the toml)
  copy:
    src: "start-amazon-cloudwatch-agent"
    dest: "/opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent"
    mode: 0755
  notify: restart amazon-cloudwatch-agent

- name: enable service on boot
  service:
    name: "amazon-cloudwatch-agent"
    enabled: "yes"

- name: Add log rotation for amazon-cloudwatch-agent.log
  copy:
    dest: '/etc/logrotate.d/aws-cwa'
    owner: 'root'
    group: 'root'
    content: |
        /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log {
            size 50M
            rotate 5
            compress
            missingok
            copytruncate
        }
